// ---- STYLES ----
export const styles = {
  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    width: "100%",
    backgroundColor: "#0a0a0a",
    backgroundImage:
      "radial-gradient(circle at 50% 50%, rgba(255,100,0,0.21) 1px, transparent 1.85px), radial-gradient(circle at 50% 50%, rgba(255,92,0,0.09) 0px, transparent 9.6px), radial-gradient(circle at 50% 50%, rgba(255,170,40,0.04) 0px, transparent 13.5px)",
    backgroundSize: "40px 40px",
    fontFamily: "'DM Sans', sans-serif",
    color: "#fff",
  },
  /** Fills space between nav and footer so the footer stays at the bottom on short pages. */
  appMain: { flex: 1, display: "flex", flexDirection: "column", minHeight: 0, width: "100%" },
  nav: { display:"flex", flexShrink:0, justifyContent:"space-between", alignItems:"center", padding:"0.35rem 1.5rem", background:"rgba(10,10,10,0.97)", backdropFilter:"blur(14px)", WebkitBackdropFilter:"blur(14px)", position:"sticky", top:0, zIndex:999, borderBottom:"1px solid #1a1a1a" },
  navLogo: { display:"flex", alignItems:"center", gap:4, cursor:"pointer" },
  navLogoWing: { fontSize:24 },
  navBrand: { fontFamily:"'Bebas Neue', sans-serif", fontSize:30, letterSpacing:1, color:"#fff" },
  navBrandAccent: { color:"#f5a623" },
  navStart: { display:"flex", alignItems:"center", gap:18, minWidth:0 },
  navLinks: { display:"flex", gap:10, alignItems:"center", flexWrap:"wrap" },
  navActions: { display:"flex", gap:12, alignItems:"center" },
  navBtn: { background:"transparent", border:"1px solid #333", color:"#fff", padding:"5px 14px", borderRadius:4, cursor:"pointer", fontFamily:"'DM Sans',sans-serif", fontWeight:600, fontSize:13, letterSpacing:1, transition:"all 0.2s" },

  landing: { paddingBottom:0 },
  /* Shorter vertical footprint than full-viewport + center so ORDER NOW / PICK UP stay in view on laptop 100% zoom */
  hero: { display:"flex", alignItems:"flex-start", justifyContent:"space-between", minHeight:"auto", padding:"1.1rem clamp(1.5rem, 4vw, 4.5rem) 2rem clamp(1.5rem, 4vw, 4.5rem)", position:"relative", overflow:"visible" },
  /* Wraps glow + wing cluster so the radial sits behind the chicken, not offset in the column */
  heroVisualCluster: {
    position:"relative",
    width:"100%",
    height:"100%",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    overflow:"visible",
  },
  /* Positioning only — pulse animations stay on .hero-visual-glow (avoids transform conflicts) */
  heroGlowAnchor: {
    position:"absolute",
    left:"50%",
    top:"50%",
    transform:"translate(-50%, -50%)",
    width:"min(118%, 560px)",
    height:"min(118%, 560px)",
    aspectRatio:"1",
    zIndex:0,
    pointerEvents:"none",
  },
  heroContent: { maxWidth:760, zIndex:1 },
  heroEyebrow: { display:"inline-block", background:"rgba(255,77,0,0.12)", border:"1px solid rgba(255,77,0,0.3)", borderRadius:4, padding:"5px 14px", fontSize:11, fontWeight:700, letterSpacing:4, color:"#FFD102", margin:0, marginBottom:26, willChange:"transform, opacity", animation:"slideLeft 0.9s cubic-bezier(0.23,1,0.32,1) both" },
  heroTitle: { fontFamily:"'Black Han Sans', sans-serif", fontSize:"clamp(64px, 10vw, 128px)", lineHeight:0.9, letterSpacing:"0.04em", margin:"0 0 26px 0", paddingRight:"0.08em", display:"inline-block", transformOrigin:"top left", willChange:"transform, opacity", animation:"heroTitleIn 1.1s cubic-bezier(0.23,1,0.32,1) 0.15s both" },
  heroTitleWings: { display:"block", color:"#fff", width:"fit-content" },
  heroTitleAccent: { display:"block", color:"#f5a623", WebkitTextStroke:"2px #f52323", WebkitTextFillColor:"transparent", width:"fit-content" },
  heroTitleGradient: { display:"block", backgroundImage:"linear-gradient(90deg, #ff4d00, #ffd500, #ff4d00)", backgroundSize:"200% 100%", backgroundPosition:"200% 0", WebkitBackgroundClip:"text", backgroundClip:"text", WebkitTextFillColor:"transparent", color:"transparent", paddingRight:"0.06em", width:"fit-content", willChange:"transform, background-position", animation:"heroTitleShimmer 3s linear infinite, heroTitleGlitch 5s linear infinite" },
  heroSub: { color:"#cc8855", fontSize:18, lineHeight:1.5, marginBottom:28, willChange:"transform, opacity", animation:"slideFireRight 0.8s cubic-bezier(0.23,1,0.32,1) 0.4s both" },
  heroButtons: { opacity:0, willChange:"transform, opacity", animation:"fadeSlideUp 0.8s cubic-bezier(0.23,1,0.32,1) 0.6s both" },
  btnPrimary: { background:"#f5a623", color:"#0a0a0a", border:"none", padding:"14px 32px", fontFamily:"'Bebas Neue',sans-serif", fontSize:20, letterSpacing:2, cursor:"pointer", borderRadius:4, transition:"transform 0.2s" },
  btnSecondary: { background:"transparent", color:"#fff", border:"2px solid #fff", padding:"14px 32px", fontFamily:"'Bebas Neue',sans-serif", fontSize:20, letterSpacing:2, cursor:"pointer", borderRadius:4, transition:"all 0.2s" },
  heroImageBlock: { position:"relative", width:"clamp(360px, 42vw, 620px)", height:"clamp(360px, 42vw, 620px)", flexShrink:0, marginRight:"clamp(0.75rem, 2.5vw, 3rem)" },
  wingEmojis: { position:"relative", zIndex:1, width:"100%", height:"100%", maxWidth:520, display:"flex", alignItems:"center", justifyContent:"center", overflow:"visible" },
  heroCenterWing: { position:"relative", zIndex:2, fontSize:"clamp(130px, 16vw, 200px)", filter:"drop-shadow(0 0 50px rgba(255,120,0,0.5)) drop-shadow(0 0 100px rgba(255,80,0,0.25))", animation:"gentleFloat 5s ease-in-out infinite" },
  bigWing: { position:"absolute", userSelect:"none", top:"26%", left:"32%" },

  menuPage: {
    /* Slightly tighter side margins so the menu column (incl. category strip) can use more width */
    padding:"0 clamp(0.75rem, 2.5vw, 3rem) 4rem",
  },
  /** Cart (empty): horizontal + bottom; top gap mostly from cartPageShell paddingTop. */
  cartMenuPageEmpty: {
    padding:"clamp(0.5rem, 1.5vw, 1.25rem) clamp(0.75rem, 2.5vw, 3rem) 4rem",
  },
  /**
   * Fills `appMain` for layout; transparent so the dotted `styles.app` background shows
   * around the yellow `cartMenuSurface` / empty-state panel.
   */
  cartPageShell: {
    flex:1,
    display:"flex",
    flexDirection:"column" as const,
    width:"100%",
    minHeight:0,
    backgroundColor:"transparent",
    paddingTop:"clamp(1.5rem, 3.5vw, 3rem)",
    boxSizing:"border-box" as const,
  },
  menuSurface: {
    /* Was calc(100vw - 360px) — below ~360px that goes negative and collapses the column. */
    /* Wider cap so the sticky category bar can fit ~14 pills without horizontal scroll on desktop. */
    maxWidth:"min(1720px, 100%)",
    margin:"0 auto",
    boxSizing:"border-box",
    width:"100%",
    overflow:"visible",
    /* No top padding: sticky stack supplies spacing; avoids a light band above the bar */
    padding:"0 clamp(0.75rem, 2vw, 2rem) clamp(1.25rem, 2vw, 2rem)",
    borderRadius:"0 0 32px 32px",
    background:"#f8c676",
    border:"1px solid rgba(255,255,255,0.28)",
    boxShadow:"0 26px 70px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.22)",
  },
  menuHeader: { textAlign:"center", marginBottom:32 },
  menuTitle: { fontFamily:"'Bebas Neue',sans-serif", fontSize:72, letterSpacing:6, margin:0, color:"#170f09" },
  menuSub: { color:"#5c432f", fontSize:16, marginBottom:24 },
  filterRow: { display:"flex", gap:10, justifyContent:"center" },
  filterBtn: { background:"transparent", border:"1px solid #333", color:"#888", padding:"8px 24px", fontFamily:"'Bebas Neue',sans-serif", fontSize:18, letterSpacing:2, cursor:"pointer", borderRadius:4, transition:"all 0.2s" },
  filterBtnActive: { borderColor:"#f5a623", color:"#f5a623" },
  menuGrid: {
    display:"grid",
    /* Use wider columns on larger screens so the first fold does not overload with too many cards. */
    gridTemplateColumns:"repeat(auto-fill, minmax(min(clamp(228px, 19vw, 272px), 100%), 1fr))",
    gap:"clamp(12px, 1.4vw, 16px)",
    justifyContent:"center",
    alignItems:"stretch",
    width:"100%",
    minWidth:0,
  },
  menuCard: {
    background:"linear-gradient(180deg, rgba(37,31,26,0.98) 0%, rgba(25,21,18,0.98) 100%)",
    border:"1px solid rgba(255, 232, 197, 0.12)",
    borderRadius:0,
    overflow:"hidden",
    display:"flex",
    flexDirection:"column",
    height:"100%",
    minHeight:"clamp(210px, 27svh, 294px)",
    transition:"box-shadow 0.22s, border-color 0.22s",
    cursor:"default",
    boxShadow:"0 14px 26px rgba(23, 18, 13, 0.2), inset 0 1px 0 rgba(255,255,255,0.03)",
  },
  menuCardEmoji: {
    fontSize:56,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    minHeight:"clamp(78px, 11svh, 108px)",
    padding:"clamp(10px, 1.5svh, 12px) 0",
    background:"linear-gradient(180deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%)",
    borderBottom:"1px solid rgba(255,255,255,0.06)",
  },
  menuCardBody: {
    padding:"clamp(12px, 1.7svh, 14px) clamp(12px, 1vw, 14px) clamp(13px, 1.9svh, 15px)",
    display:"flex",
    flexDirection:"column",
    flex:"1 1 auto",
    minHeight:0,
  },
  menuCardCopy: {
    display:"flex",
    flexDirection:"column",
    gap:"clamp(8px, 1.2svh, 10px)",
    minHeight:"clamp(78px, 10svh, 102px)",
  },
  menuCardName: {
    fontFamily:"'DM Sans', sans-serif",
    fontSize:"clamp(17px, 1.9svh, 18px)",
    fontWeight:700,
    lineHeight:1.28,
    letterSpacing:0.15,
    minHeight:"calc(1.28em * 2)",
    margin:0,
    color:"#fff3e3",
  },
  menuCardSaladSizes: {
    fontFamily:"'DM Sans', sans-serif",
    fontSize:"clamp(12px, 1.38svh, 13px)",
    fontWeight:600,
    lineHeight:1.35,
    letterSpacing:"0.04em",
    margin:0,
    marginTop:"-2px",
  },
  menuCardDesc: {
    color:"var(--menu-item-desc-color, #FFBC00)",
    fontSize:"clamp(13px, 1.52svh, 15px)",
    fontWeight:600,
    lineHeight:1.5,
    letterSpacing:"0.01em",
    margin:0,
    minHeight:"calc(1.5em * 2)",
  },
  menuCardDescPlaceholder: {
    minHeight:"calc(1.5em * 2)",
  },
  menuCardFooter: {
    display:"flex",
    justifyContent:"space-between",
    alignItems:"center",
    gap:"clamp(8px, 1.2svh, 10px)",
    marginTop:"auto",
    paddingTop:"clamp(10px, 1.7svh, 14px)",
    borderTop:"1px solid rgba(255,255,255,0.06)",
  },
  menuCardPrice: { color:"#fff4e6", fontFamily:"'Bebas Neue',sans-serif", fontSize:"clamp(19px, 2.1svh, 20px)", letterSpacing:1, flexShrink:0 },
  addBtn: {
    width:"auto",
    minWidth:"clamp(92px, 9vw, 104px)",
    background:"rgba(255,255,255,0.04)",
    border:"1px solid rgba(255,255,255,0.12)",
    color:"#fff4e6",
    padding:"clamp(8px, 1.3svh, 9px) clamp(11px, 1vw, 12px)",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(13px, 1.4svh, 14px)",
    letterSpacing:1.2,
    cursor:"pointer",
    borderRadius:4,
    transition:"all 0.2s",
    whiteSpace:"nowrap",
    marginLeft:"auto",
  },
  addBtnActive: { background:"#f5a623", color:"#0a0a0a", borderColor:"#f5a623" },
  menuCardQtyGroup: {
    display:"flex",
    alignItems:"center",
    gap:6,
    marginLeft:"auto",
    background:"#f5a623",
    borderRadius:4,
    padding:"3px 4px",
    border:"1px solid #f5a623",
  },
  menuCardQtyBtn: {
    width:"clamp(26px, 2.6vw, 30px)",
    height:"clamp(26px, 2.6vw, 30px)",
    background:"#0a0a0a",
    color:"#f5a623",
    border:"none",
    borderRadius:3,
    cursor:"pointer",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(15px, 1.7svh, 17px)",
    lineHeight:1,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    padding:0,
  },
  menuCardQtyValue: {
    minWidth:18,
    color:"#0a0a0a",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(15px, 1.7svh, 17px)",
    letterSpacing:1,
    textAlign:"center" as const,
    fontWeight:700,
  },

  cartPage: {
    padding:"2rem clamp(0.75rem, 4vw, 4.75rem) 4rem",
    display:"flex",
    justifyContent:"center",
  },
  cartShell: {
    width:"100%",
    maxWidth:760,
    display:"flex",
    flexDirection:"column" as const,
    gap:20,
  },
  cartCard: {
    background:"linear-gradient(180deg, rgba(37,31,26,0.98) 0%, rgba(25,21,18,0.98) 100%)",
    border:"1px solid rgba(255, 232, 197, 0.12)",
    borderRadius:6,
    padding:"clamp(18px, 2vw, 26px)",
    color:"#fff4e6",
    boxShadow:"0 14px 26px rgba(23, 18, 13, 0.2), inset 0 1px 0 rgba(255,255,255,0.03)",
  },
  cartHeaderRow: {
    display:"flex",
    alignItems:"center",
    justifyContent:"space-between",
    gap:12,
    marginBottom:14,
  },
  cartHeaderTitle: {
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(28px, 3vw, 36px)",
    letterSpacing:3,
    margin:0,
    color:"#f5a623",
  },
  cartScheduleRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    gap:10,
    alignItems:"center",
    justifyContent:"space-between",
    fontSize:13,
    color:"rgba(255, 244, 230, 0.84)",
  },
  cartScheduleChips: { display:"flex", gap:10, flexWrap:"wrap" as const },
  cartScheduleChip: {
    background:"rgba(255,255,255,0.05)",
    border:"1px solid rgba(255,255,255,0.12)",
    padding:"6px 12px",
    borderRadius:4,
  },
  cartScheduleEdit: {
    color:"#f5a623",
    textDecoration:"none",
    fontWeight:600,
    fontSize:13,
  },
  cartLineRow: {
    display:"flex",
    gap:14,
    padding:"14px 0",
    borderTop:"1px solid rgba(255,255,255,0.06)",
    alignItems:"flex-start",
  },
  cartLineRowFirst: {
    display:"flex",
    gap:14,
    padding:"4px 0 14px",
    alignItems:"flex-start",
  },
  cartLineThumbWrap: {
    width:72,
    minWidth:72,
    height:72,
    borderRadius:6,
    overflow:"hidden",
    background:"rgba(255,255,255,0.04)",
    border:"1px solid rgba(255,255,255,0.08)",
    boxShadow:"inset 0 1px 0 rgba(255,255,255,0.04)",
  },
  cartLineThumbImage: {
    width:"100%",
    height:"100%",
    objectFit:"cover" as const,
    display:"block",
  },
  cartLineThumbPlaceholder: {
    width:"100%",
    height:"100%",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    background:"linear-gradient(135deg, rgba(245,166,35,0.24), rgba(255,98,0,0.18))",
    color:"#fff4e6",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:26,
    letterSpacing:1.5,
  },
  cartLineInfo: { flex:1, minWidth:0 },
  cartLineName: {
    margin:0,
    fontFamily:"'DM Sans',sans-serif",
    fontSize:16,
    fontWeight:700,
    color:"#fff4e6",
  },
  cartLineSubtitle: {
    margin:"4px 0 0",
    fontSize:13,
    color:"rgba(255, 244, 230, 0.72)",
    lineHeight:1.4,
  },
  cartLineRemoved: {
    margin:"4px 0 0",
    fontSize:12,
    color:"#ff8a73",
    lineHeight:1.4,
  },
  cartLineNotes: {
    margin:"4px 0 0",
    fontSize:12,
    fontStyle:"italic" as const,
    color:"rgba(255, 244, 230, 0.6)",
    lineHeight:1.4,
  },
  cartLineQtyRow: {
    display:"flex",
    alignItems:"center",
    gap:8,
    marginTop:10,
  },
  cartLineQtyBtn: {
    width:30,
    height:30,
    background:"#0a0a0a",
    border:"1px solid rgba(255,255,255,0.18)",
    color:"#f5a623",
    borderRadius:3,
    cursor:"pointer",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:18,
    lineHeight:1,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    padding:0,
  },
  cartLineQtyValue: {
    minWidth:24,
    textAlign:"center" as const,
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:18,
    color:"#fff4e6",
  },
  cartLineRight: {
    display:"flex",
    flexDirection:"column" as const,
    alignItems:"flex-end",
    justifyContent:"space-between",
    minWidth:96,
    textAlign:"right" as const,
    gap:8,
  },
  cartLinePrice: {
    color:"#fff4e6",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:20,
    letterSpacing:1,
  },
  cartLineActions: { display:"flex", gap:6, flexWrap:"wrap" as const, justifyContent:"flex-end" },
  cartLineActionBtn: {
    background:"transparent",
    border:"1px solid rgba(255,255,255,0.18)",
    color:"#fff4e6",
    padding:"5px 10px",
    borderRadius:4,
    cursor:"pointer",
    fontFamily:"'DM Sans',sans-serif",
    fontWeight:600,
    fontSize:11,
    letterSpacing:0.5,
  },
  cartLineRemoveBtn: {
    background:"transparent",
    border:"1px solid rgba(255, 138, 115, 0.4)",
    color:"#ff8a73",
    padding:"5px 10px",
    borderRadius:4,
    cursor:"pointer",
    fontFamily:"'DM Sans',sans-serif",
    fontWeight:600,
    fontSize:11,
    letterSpacing:0.5,
  },
  cartSummaryBox: {
    marginTop:18,
    paddingTop:16,
    borderTop:"1px solid rgba(255,255,255,0.08)",
    display:"flex",
    flexDirection:"column" as const,
    gap:8,
  },
  cartSummaryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 14,
    color: "#374151",
  },
  cartSummaryAmount: {
    color: "#111827",
    fontWeight: 700 as const,
  },
  cartSummaryTotal: {
    display:"flex",
    justifyContent:"space-between",
    marginTop:8,
    paddingTop:12,
    borderTop:"2px solid rgba(255, 244, 230, 0.25)",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:24,
    letterSpacing:2,
    color:"#fff4e6",
  },
  cartCheckoutBtn: {
    marginTop:18,
    width:"100%",
    background:"#f5a623",
    color:"#0a0a0a",
    border:"none",
    padding:"14px 24px",
    borderRadius:4,
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:20,
    letterSpacing:2,
    cursor:"pointer",
  },
  cartEmpty: {
    textAlign:"center" as const,
    padding:"3rem 1rem",
    color:"rgba(255, 244, 230, 0.7)",
  },
  cartEmptyTitle: {
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:32,
    letterSpacing:3,
    color:"#0C0300",
    margin:"0 0 8px",
  },
  cartEmptySub: {
    margin:"8px 0 0",
    fontSize:16,
    color:"#0C0300",
    fontFamily:"'DM Sans',sans-serif",
    lineHeight:1.5,
  },
  /**
   * Empty cart: one yellow sheet (menu-surface style) containing “YOUR ORDER” + empty copy.
   */
  cartEmptyYellowPanel: {
    textAlign:"center" as const,
    maxWidth:1080,
    margin:"0 auto",
    padding:"clamp(1.35rem, 2.4vw, 2rem) clamp(1.25rem, 2vw, 2rem) clamp(1.75rem, 2.8vw, 2.5rem)",
    borderRadius:"clamp(20px, 2.5vw, 32px)",
    background:"#f8c676",
    border:"1px solid rgba(255,255,255,0.28)",
    boxShadow:"0 26px 70px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.22)",
  },
  /** Inner block below the title (no second yellow layer). */
  cartEmptyPanelBody: {
    textAlign:"center" as const,
    padding:"clamp(1.1rem, 2vw, 1.5rem) 0 0",
    marginTop:"clamp(0.4rem, 1vw, 0.75rem)",
    borderTop:"1px solid rgba(23, 15, 9, 0.22)",
  },
  /** Empty cart: no outer yellow sheet — only padding, dots show through. */
  cartMenuSurfaceEmpty: {
    maxWidth:"min(1720px, 100%)",
    margin:"0 auto",
    boxSizing:"border-box",
    width:"100%",
    overflow:"visible",
    padding:"clamp(1rem, 2vw, 1.5rem) clamp(0.75rem, 2vw, 2rem) clamp(1.5rem, 2.5vw, 2.5rem)",
    background:"transparent",
    border:"none",
    boxShadow:"none",
  },
  cartLinkPrimary: {
    display:"inline-block",
    marginTop:18,
    background:"#f5a623",
    color:"#0a0a0a",
    padding:"10px 22px",
    borderRadius:4,
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:18,
    letterSpacing:2,
    textDecoration:"none",
  },

  /** Yellow menu surface wrapping the cart (rounded on all corners; centered in cartPageShell). */
  cartMenuSurface: {
    maxWidth:"min(1720px, 100%)",
    margin:"0 auto",
    boxSizing:"border-box",
    width:"100%",
    overflow:"visible",
    padding:"clamp(1rem, 2vw, 1.5rem) clamp(0.75rem, 2vw, 2rem) clamp(1.5rem, 2.5vw, 2.5rem)",
    borderRadius:"clamp(20px, 2.5vw, 32px)",
    background:"#f8c676",
    border:"1px solid rgba(255,255,255,0.28)",
    boxShadow:"0 26px 70px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.22)",
  },
  cartMenuInner: {
    width:"100%",
    maxWidth:1200,
    margin:"0 auto",
  },
  cartLayoutRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    alignItems:"flex-start",
    gap:28,
    width:"100%",
  },
  cartItemsColumn: {
    flex:"1 1 360px",
    minWidth:0,
  },
  /** Sticky wrapper: order summary column (see .wk-cart-right-column in global-style). */
  cartRightColumn: {
    flex:"1 1 300px",
    maxWidth:"100%",
    minWidth:"min(320px, 100%)",
    display:"flex",
    flexDirection:"column" as const,
    gap:14,
  },
  cartOrderSummaryColumn: {
    flex:"1 1 300px",
    maxWidth:"100%",
  },
  cartOrderTitle: {
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(40px, 5vw, 72px)",
    letterSpacing:6,
    margin:"0 0 clamp(12px, 2vw, 20px)",
    textAlign:"center" as const,
    color:"#0C0300",
  },
  /** YOUR ORDER row: title left, pickup/delivery right (above accent line). */
  cartOrderTopRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    alignItems:"flex-start",
    justifyContent:"space-between",
    gap:16,
    width:"100%",
  },
  cartOrderHeaderBlock: {
    marginBottom:0,
    textAlign:"left" as const,
    flex:"1 1 240px",
    minWidth:0,
  },
  /** Wraps CartOrderSettings in the top row (see .wk-cart-order-settings-top in global-style). */
  cartOrderSettingsSlot: {
    flex:"1 1 280px",
    maxWidth:"min(440px, 100%)",
    minWidth:0,
  },
  cartOrderTitleLeft: {
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(32px, 4vw, 56px)",
    letterSpacing:5,
    margin:0,
    marginBottom:12,
    color:"#0C0300",
  },
  /** Padding so a soft shadow on the dark line does not clip. */
  cartOrderAccentLineTrack: {
    width:"100%",
    marginTop:12,
    marginBottom:20,
    paddingTop:4,
    paddingBottom:6,
    boxSizing:"border-box" as const,
  },
  /** Solid dark rule on light yellow (no left fade). */
  cartOrderAccentLine: {
    width:"100%",
    height:2,
    borderRadius:2,
    background:"#0C0300",
    boxShadow:"0 1px 0 rgba(255, 255, 255, 0.1)",
  },
  cartItemCountLabel: {
    margin: "0 0 24px",
    fontFamily: "'DM Sans',sans-serif",
    fontSize: "clamp(20px, 2.6vw, 28px)",
    fontWeight: 600,
    letterSpacing: 0.45,
    lineHeight: 1.35,
    color: "#0C0300",
  },
  /** Per-line item card — dark brown surface. */
  cartItemLineCard: {
    background:"#3a2618",
    border:"1px solid rgba(245, 166, 35, 0.28)",
    borderRadius:16,
    padding:"clamp(14px, 2vw, 18px)",
    marginBottom:16,
    boxShadow:"0 8px 28px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,210,140,0.08)",
  },
  cartItemThumbWrap: {
    borderRadius:12,
    overflow:"hidden",
    background:"rgba(255,255,255,0.06)",
    border:"1px solid rgba(255, 255, 255, 0.1)",
  },
  cartItemThumbImage: {
    width:"100%",
    height:"100%",
    objectFit:"cover" as const,
    display:"block",
  },
  cartItemThumbPlaceholder: {
    width:"100%",
    height:"100%",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    background:"linear-gradient(135deg, rgba(245,166,35,0.22), rgba(255,98,0,0.14))",
    color:"#fff4e6",
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:30,
    letterSpacing:1.5,
  },
  cartItemCardBody: { flex:1, minWidth:0 },
  cartItemTitleRow: {
    display:"flex",
    justifyContent:"space-between",
    alignItems:"flex-start",
    gap:12,
    marginBottom:6,
  },
  cartItemNameLight: {
    margin:0,
    fontFamily:"'DM Sans',sans-serif",
    fontSize:"clamp(15px, 1.6vw, 17px)",
    fontWeight:700,
    color:"#fff8ef",
    lineHeight:1.25,
    flex:1,
    minWidth:0,
  },
  cartItemPriceTop: {
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:"clamp(19px, 2.2vw, 22px)",
    letterSpacing:1,
    color:"#fff4e6",
    flexShrink:0,
  },
  cartItemDescLine: {
    margin: "2px 0 0",
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 1.45,
  },
  /** Line-item summary under title (`Category: ` + selection inline, not edge-to-edge). */
  cartItemLineDesc: {
    margin:"2px 0 0",
    fontSize:15,
    lineHeight:1.45,
  },
  cartItemLineDescLabel: {
    color:"#ffffff",
  },
  /** Value after "Label: " in structured cart lines. */
  cartItemLineDescValue: {
    color:"#FFD500",
  },
  /** Full-width line when no `Category: value` parse (fallback). */
  cartItemLineDescSingle: {
    color:"rgba(255, 244, 230, 0.88)",
  },
  cartItemNoteRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    alignItems:"baseline",
    gap:4,
    marginTop:10,
    fontSize:13,
    fontStyle:"normal" as const,
    lineHeight:1.45,
  },
  cartItemNoteLabel: {
    color:"rgba(255, 255, 255, 0.92)",
    fontWeight:600,
  },
  cartItemNoteValue: {
    color:"#FFD500",
    fontStyle:"normal" as const,
    fontWeight:400,
  },
  cartItemFooterRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    alignItems:"center",
    justifyContent:"space-between",
    gap:12,
    marginTop:14,
    paddingTop:12,
    borderTop:"1px solid rgba(255, 255, 255, 0.1)",
  },
  /** Shell for .cart-item-qty-* classes in global-style. */
  cartItemQtyGroup: {
    display:"inline-flex",
    alignItems:"center",
    gap:2,
  },
  cartItemQtyValue: {
    minWidth:28,
    textAlign:"center" as const,
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:17,
    letterSpacing:1,
    fontWeight:700 as const,
    color:"#fff8ef",
  },
  cartItemActionRow: { display:"flex", gap:8, flexWrap:"wrap" as const },
  cartItemBtnEdit: {
    /* hover via .cart-line-btn-edit */
    background:"rgba(255, 248, 240, 0.22)",
    border:"1px solid rgba(255, 244, 230, 0.5)",
    color:"#fff8ef",
    padding:"8px 14px",
    borderRadius:8,
    cursor:"pointer",
    fontFamily:"'DM Sans',sans-serif",
    fontWeight:600,
    fontSize:12,
    boxShadow:"0 2px 8px rgba(0,0,0,0.15)",
    transition:"background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  cartItemBtnRemove: {
    background:"rgba(255, 120, 60, 0.2)",
    border:"1px solid rgba(255, 170, 110, 0.65)",
    color:"#ffe0d4",
    padding:"8px 14px",
    borderRadius:8,
    cursor:"pointer",
    fontFamily:"'DM Sans',sans-serif",
    fontWeight:600,
    fontSize:12,
    boxShadow:"0 2px 8px rgba(0,0,0,0.12)",
    transition:"background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  cartSummaryPanel: {
    background:"#28231D",
    border:"1px solid rgba(255, 232, 197, 0.14)",
    borderRadius:16,
    padding:"clamp(16px, 2vw, 22px)",
    marginTop:8,
  },
  cartOrderSummaryCard: {
    background: "#FFFFFF",
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    padding: "clamp(16px, 1.8vw, 20px) clamp(18px, 2vw, 24px) 14px",
    boxShadow: "0 12px 40px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.02)",
  },
  cartOrderSummaryTitle: {
    fontFamily: "'Libre Baskerville', Georgia, 'Times New Roman', serif",
    fontSize: 22,
    fontWeight: 700,
    color: "#111827",
    margin: "0 0 18px",
    letterSpacing: 0.5,
  },
  cartPromoRow: {
    display:"flex",
    gap:10,
    marginBottom:20,
    alignItems:"stretch",
  },
  cartPromoInput: {
    flex: 1,
    minWidth: 0,
    background: "#f9fafb",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 14,
    color: "#111827",
    fontFamily: "'DM Sans',sans-serif",
    outline: "none",
  },
  cartPromoApplyBtn: {
    flexShrink: 0,
    background: "#f3f4f6",
    border: "1px solid #e2e8f0",
    color: "#374151",
    padding: "10px 18px",
    borderRadius: 8,
    fontFamily: "'DM Sans',sans-serif",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    transition: "background 0.2s ease, border-color 0.2s ease, transform 0.2s ease",
  },
  cartSeeCouponsBtn: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    background: "#FFF7ED",
    border: "1px solid rgba(249, 115, 22, 0.3)",
    color: "#F97316",
    padding: "12px 16px",
    borderRadius: 10,
    fontFamily: "'DM Sans',sans-serif",
    fontWeight: 800,
    fontSize: 16,
    cursor: "pointer",
    marginBottom: 12,
    transition: "background 0.2s ease, transform 0.15s ease",
  },
  cartSeeCouponsIcon: {
    fontSize:18,
    lineHeight:1,
  },
  cartRewardBlockedNote: {
    fontSize: 12,
    color: "#D97706",
    margin: "-4px 0 12px",
    fontFamily: "'DM Sans',sans-serif",
  },
  couponsModalOverlay: {
    position:"fixed" as const,
    inset:0,
    background:"rgba(15, 23, 42, 0.45)",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    padding:24,
    zIndex:1000,
  },
  couponsModalCard: {
    width:"min(500px, 100%)",
    maxHeight:"85vh",
    overflowY:"auto" as const,
    background:"#ffffff",
    border:"2px solid #f97316",
    borderRadius:24,
    padding:"36px 40px",
    color:"#17120d",
    fontFamily:"'DM Sans',sans-serif",
    boxShadow:"0 24px 48px -12px rgba(15, 23, 42, 0.12), 0 0 0 1px rgba(249, 115, 22, 0.08)",
  },
  couponsModalHeader: {
    marginBottom:8,
  },
  couponsModalEyebrow: {
    fontSize:11,
    fontWeight:700,
    textTransform:"uppercase" as const,
    letterSpacing:"0.1em",
    color:"#f97316",
    margin:"0 0 20px 0",
    textAlign:"center" as const,
  },
  couponsModalTitleRow: {
    display:"flex",
    alignItems:"flex-start",
    justifyContent:"space-between",
    gap:16,
    marginBottom:24,
  },
  couponsModalTitleBlock: {
    flex:1,
    minWidth:0,
  },
  couponsModalTitle: {
    fontSize:26,
    fontWeight:800,
    margin:0,
    color:"#0f172a",
    letterSpacing:"-0.02em",
    lineHeight:1.2,
  },
  couponsModalClose: {
    background:"#f8fafc",
    border:"1px solid #e2e8f0",
    width:36,
    height:36,
    borderRadius:12,
    color:"#475569",
    fontSize:16,
    fontWeight:600,
    cursor:"pointer",
    flexShrink:0,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    lineHeight:1,
  },
  couponCard: {
    display:"flex",
    alignItems:"center",
    gap:14,
    width:"100%",
    padding:16,
    background:"linear-gradient(135deg, rgba(249, 115, 22, 0.08), rgba(255, 247, 237, 0.95))",
    borderWidth:1,
    borderStyle:"solid" as const,
    borderColor:"rgba(249, 115, 22, 0.35)",
    borderRadius:16,
    color:"#17120d",
    fontFamily:"'DM Sans',sans-serif",
    cursor:"pointer",
    textAlign:"left" as const,
    transition:"transform 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease",
  },
  couponCardApplied: {
    background:"linear-gradient(135deg, rgba(16, 185, 129, 0.1), rgba(236, 253, 245, 0.98))",
    borderWidth:1,
    borderStyle:"solid" as const,
    borderColor:"rgba(16, 185, 129, 0.45)",
    cursor:"default" as const,
  },
  couponCardIcon: {
    width:48,
    height:48,
    borderRadius:14,
    background:"#fff7ed",
    border:"1px solid rgba(249, 115, 22, 0.2)",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    fontSize:24,
    flexShrink:0,
  },
  couponCardBody: {
    flex:1,
    minWidth:0,
    display:"flex",
    flexDirection:"column" as const,
    gap:2,
  },
  couponCardTitle: {
    fontSize:15,
    fontWeight:700,
    color:"#0f172a",
  },
  couponCardSubtitle: {
    fontSize:12,
    color:"#64748b",
    fontWeight:600,
  },
  couponCardMeta: {
    fontSize:12,
    color:"#94a3b8",
    marginTop:4,
    lineHeight:1.4,
  },
  couponCardAction: {
    fontSize:13,
    fontWeight:700,
    color:"#ea580c",
    flexShrink:0,
  },
  couponsEmpty: {
    display:"flex",
    flexDirection:"column" as const,
    alignItems:"center",
    textAlign:"center" as const,
    justifyContent:"center",
    padding:"40px 20px 28px",
    minHeight:220,
  },
  couponsEmptyIcon: {
    width:88,
    height:88,
    borderRadius:999,
    background:"#f1f5f9",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    fontSize:40,
    marginBottom:20,
    border:"1px solid #e2e8f0",
  },
  couponsEmptyTitle: {
    fontSize:17,
    fontWeight:700,
    color:"#0f172a",
    margin:"0 0 8px 0",
  },
  couponsEmptyDesc: {
    fontSize:14,
    color:"#64748b",
    margin:0,
    maxWidth:320,
    lineHeight:1.55,
    fontWeight:500,
  },
  couponRemoveBtn: {
    marginTop:14,
    width:"100%",
    background:"#fffbeb",
    border:"1px solid rgba(234, 88, 12, 0.35)",
    color:"#c2410c",
    padding:"10px 14px",
    borderRadius:12,
    fontFamily:"'DM Sans',sans-serif",
    fontWeight:600,
    fontSize:13,
    cursor:"pointer",
  },
  cartTipLabel: {
    fontFamily: "'Libre Baskerville', Georgia, 'Times New Roman', serif",
    fontSize: 22,
    fontWeight: 700,
    color: "#111827",
    margin: "0 0 18px",
    letterSpacing: "0.5px",
  },
  cartTipSegmentRow: {
    display:"flex",
    flexWrap:"wrap" as const,
    gap:8,
    marginBottom:20,
  },
  cartOrderSummaryDivider: {
    height: 1,
    background: "#e2e8f0",
    margin: "4px 0 14px",
    border: "none",
  },
  cartOrderSummaryTotalLabel: {
    fontFamily: "'Libre Baskerville', Georgia, serif",
    fontSize: 26,
    fontWeight: 700,
    color: "#111827",
    letterSpacing: 1,
  },
  cartOrderSummaryTotalValue: {
    fontFamily: "'Libre Baskerville', Georgia, serif",
    fontSize: 28,
    fontWeight: 700,
    color: "#F97316",
    letterSpacing: 0.5,
  },
  /** Legacy flat style; checkout uses .cart-checkout-fire-btn (sauces page gradient). */
  cartCheckoutBtnWide: {
    marginTop:18,
    width:"100%",
    background:"#f5a623",
    color:"#0a0a0a",
    border:"none",
    padding:"16px 20px",
    borderRadius:10,
    fontFamily:"'Bebas Neue',sans-serif",
    fontSize:22,
    letterSpacing:2,
    cursor:"pointer",
    boxShadow:"0 10px 28px rgba(245, 166, 35, 0.35)",
  },

  modalOverlay: { position:"fixed", inset:0, background:"rgba(0,0,0,0.8)", backdropFilter:"blur(4px)", zIndex:200, display:"flex", alignItems:"center", justifyContent:"center", padding:16 },
  modal: { background:"#111", border:"1px solid #222", borderRadius:10, padding:32, width:"100%", maxWidth:420, maxHeight:"80vh", overflowY:"auto", position:"relative" },
  modalTitle: { fontFamily:"'Bebas Neue',sans-serif", fontSize:36, letterSpacing:4, margin:"0 0 24px", textAlign:"center" },
  cartItem: { display:"flex", justifyContent:"space-between", alignItems:"center", padding:"12px 0", borderBottom:"1px solid #1e1e1e", fontSize:15 },
  cartItemPrice: { color:"#fff4e6", fontWeight:600 },
  removeBtn: { background:"#2a0a0a", border:"none", color:"#f55", width:26, height:26, borderRadius:4, cursor:"pointer", fontSize:12 },
  cartTotal: { display:"flex", justifyContent:"space-between", fontFamily:"'Bebas Neue',sans-serif", fontSize:26, letterSpacing:3, marginTop:16, paddingTop:16, borderTop:"2px solid rgba(255, 244, 230, 0.25)", color:"#fff4e6" },
  input: { width:"100%", background:"#1a1a1a", border:"1px solid #2a2a2a", color:"#fff", padding:"12px 16px", borderRadius:4, fontSize:15, marginBottom:12, boxSizing:"border-box", outline:"none" },
  closeBtn: { display:"block", margin:"16px auto 0", background:"transparent", border:"1px solid #333", color:"#888", padding:"8px 24px", cursor:"pointer", borderRadius:4, fontFamily:"'Bebas Neue',sans-serif", fontSize:16, letterSpacing:2 },
} as const;
